{% set version = "0.0-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rebus.base
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rebus.base_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rebus.base/rebus.base_{{ version }}.tar.gz
  sha256: deeccf9ac75c3b4e8242ff481e9f95895b11fb2178b695ce303329cfbe8653d8

build:
  noarch: generic
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('rebus.base')"           # [not win]
    - "\"%R%\" -e \"library('rebus.base')\""  # [win]

about:
  home: https://github.com/richierocks/rebus.base
  license: Unlimited
  license_family: OTHER
  license_file:
    - LICENSE
  summary: Build regular expressions piece by piece using human readable code. This package contains core functionality, and is primarily intended to be used by package developers.

extra:
  recipe-maintainers:
    - conda-forge/r
